logging:
  level:
    root: warn
    com.etoos.opencv: debug
  #path: /home/ec2-user/api/log
  file:
    max-history: 7
spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:3306/doo?zeroDateTimeBehavior=convertToNull&useSSL=false
    username: ldh
    password: doo
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#mybatis:
#  type-aliases-package: com.etoos.opencv.mapper
#  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  port: 8080

elasticsearch:
  host: 3.114.156.99
  public: 3.114.156.99
  port: 9200
  alias:
    user: revu_users_local
    campaign: revu_campaigns_local
    post: revu_posts_local
  shards: 2
  replicas: 0

aws:
  s3:
    host: s3.ap-northeast-2.amazonaws.com
    bucket: cmw-ws
    region: ap-northeast-2
    key-name: system/images
    local-file-save-path: ${HOME}
file:
  upload_dir: ./images


